apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - environment-config.yaml
  - service-accounts.yaml
  - external-secrets.yaml
  - network-policy.yaml
  - storage-budget.yaml
  - storage-coordinates.yaml
  - storage/odoo-filestore.yaml
  - storage/postgresql-data.yaml
  - storage/prometheus-data.yaml
  - application-workloads.yaml
  - application-services.yaml
  - application-autoscaling.yaml
  - application-ingress.yaml
  - observability
