apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  labels:
    app.kubernetes.io/part-of: stockai
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stockai-frontend
  labels:
    app.kubernetes.io/part-of: stockai
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stockai-agent-api
  labels:
    app.kubernetes.io/part-of: stockai
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stockai-procurement-mcp
  labels:
    app.kubernetes.io/part-of: stockai
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stockai-odoo
  labels:
    app.kubernetes.io/part-of: stockai
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stockai-postgresql
  labels:
    app.kubernetes.io/part-of: stockai
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stockai-automation
  labels:
    app.kubernetes.io/part-of: stockai
automountServiceAccountToken: false
