apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubernetes-sigs/metrics-server/manifests/overlays/release?ref=v0.9.0
  - github.com/kubernetes/kube-state-metrics/examples/standard?ref=v2.19.1

patches:
  - path: metrics-server-kubelet-tls.yaml
    target:
      group: apps
      kind: Deployment
      name: metrics-server
      version: v1
  - path: control-plane-deployment.yaml
    target:
      group: apps
      kind: Deployment
      name: metrics-server
      version: v1
  - path: control-plane-deployment.yaml
    target:
      group: apps
      kind: Deployment
      name: kube-state-metrics
      version: v1
