apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
spec:
  controller: stockai-dev
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cron-token
spec:
  data:
  - remoteRef:
      key: arn:aws:secretsmanager:us-east-1:228281126655:secret:weam-stockai/dev/cron-token-h2SuQz
    secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
spec:
  data:
  - remoteRef:
      key: arn:aws:secretsmanager:us-east-1:228281126655:secret:weam-stockai/dev/grafana-admin-password-E2LWUx
    secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-token
spec:
  data:
  - remoteRef:
      key: arn:aws:secretsmanager:us-east-1:228281126655:secret:weam-stockai/dev/mcp-token-cPDims
    secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: odoo-api-key
spec:
  data:
  - remoteRef:
      key: arn:aws:secretsmanager:us-east-1:228281126655:secret:weam-stockai/dev/odoo-api-key-Q2imb0
    secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: odoo-database-password
spec:
  data:
  - remoteRef:
      key: arn:aws:secretsmanager:us-east-1:228281126655:secret:weam-stockai/dev/odoo-database-password-9YSX1Z
    secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: session-secret
spec:
  data:
  - remoteRef:
      key: arn:aws:secretsmanager:us-east-1:228281126655:secret:weam-stockai/dev/session-secret-WNndwq
    secretKey: value
