apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
spec:
  controller: stockai-prod
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cron-token
spec:
  data:
  - remoteRef:
      key: arn:aws:secretsmanager:us-east-1:228281126655:secret:weam-stockai/prod/cron-token-bbI51i
    secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
spec:
  data:
  - remoteRef:
      key: arn:aws:secretsmanager:us-east-1:228281126655:secret:weam-stockai/prod/grafana-admin-password-Brwczr
    secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-token
spec:
  data:
  - remoteRef:
      key: arn:aws:secretsmanager:us-east-1:228281126655:secret:weam-stockai/prod/mcp-token-9pkSer
    secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: odoo-api-key
spec:
  data:
  - remoteRef:
      key: arn:aws:secretsmanager:us-east-1:228281126655:secret:weam-stockai/prod/odoo-api-key-5n11Yp
    secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: odoo-database-password
spec:
  data:
  - remoteRef:
      key: arn:aws:secretsmanager:us-east-1:228281126655:secret:weam-stockai/prod/odoo-database-password-qAxhgx
    secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: session-secret
spec:
  data:
  - remoteRef:
      key: arn:aws:secretsmanager:us-east-1:228281126655:secret:weam-stockai/prod/session-secret-wGMeFf
    secretKey: value
