apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
spec:
  controller: stockai-prod
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cron-token
spec:
  data:
    - remoteRef:
        key: weam-stockai/prod/cron-token
      secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
spec:
  data:
    - remoteRef:
        key: weam-stockai/prod/grafana-admin-password
      secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-token
spec:
  data:
    - remoteRef:
        key: weam-stockai/prod/mcp-token
      secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: odoo-api-key
spec:
  data:
    - remoteRef:
        key: weam-stockai/prod/odoo-api-key
      secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: odoo-database-password
spec:
  data:
    - remoteRef:
        key: weam-stockai/prod/odoo-database-password
      secretKey: value
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: session-secret
spec:
  data:
    - remoteRef:
        key: weam-stockai/prod/session-secret
      secretKey: value
