- op: add
  path: /spec/template/spec/nodeSelector
  value:
    node-role.kubernetes.io/control-plane: ""
- op: add
  path: /spec/template/spec/tolerations
  value:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
